const Buildings = [
    {
        ubication: "Rosario",
        type: "Casa",
        id: 1,
        address: "Avellaneda 500",
        bathrooms: 3,
        rooms: 2,
        garage: false,
        backyard: true,
        pictures: ['/images/pexels-pixabay-208736.jpg'],
        description: "casa grande con patio y sin garage",
        rating: Array(4).fill("*"),
        price: 300000,
        isAuthorized: true,
        userId: 1
    },
    {
        ubication: "Rosario",
        type: "Casa",
        id: 2,
        address: "Avellaneda 500",
        bathrooms: 3,
        rooms: 2,
        garage: false,
        backyard: false,
        pictures: ['/images/pexels-eberhardgross-2098405.jpg'],
        description: "Casa grande sin patio y sin garage",
        rating: Array(3).fill("*"),
        price: 200000,
        isAuthorized: true,
        userId: 2
    },
    {
        ubication: "Rosario",
        type: "Casa",
        id: 3,
        address: "Avellaneda 500",
        bathrooms: 3,
        rooms: 2,
        garage: true,
        backyard: true,
        pictures: ['/images/pexels-pixasquare-1115804.jpg'],
        description: "Casa grande con patio y con garage",
        rating: Array(5).fill("*"),
        price: 500000,
        isAuthorized: false,
        userId: 3
    },
    {
        ubication: "Rosario",
        type: "Casa",
        id: 4,
        address: "Avellaneda 500",
        bathrooms: 3,
        rooms: 2,
        garage: false,
        backyard: true,
        pictures: ['/images/pexels-pixabay-208736.jpg'],
        description: "casa grande con patio y sin garage",
        rating: Array(4).fill("*"),
        price: 300000,
        isAuthorized: true,
        userId: 1
    },
    {
        ubication: "Rosario",
        type: "Casa",
        id: 5,
        address: "Avellaneda 500",
        bathrooms: 3,
        rooms: 2,
        garage: false,
        backyard: false,
        pictures: ['/images/pexels-eberhardgross-2098405.jpg'],
        description: "Casa grande sin patio y sin garage",
        rating: Array(3).fill("*"),
        price: 200000,
        isAuthorized: true,
        userId: 2
    },
    {
        ubication: "Rosario",
        type: "Casa",
        id: 6,
        address: "Avellaneda 500",
        bathrooms: 3,
        rooms: 2,
        garage: true,
        backyard: true,
        pictures: ['/images/pexels-pixasquare-1115804.jpg'],
        description: "Casa grande con patio y con garage",
        rating: Array(5).fill("*"),
        price: 500000,
        isAuthorized: false,
        userId: 3
    }
];

export default Buildings;